### ISSUE TITLE
User Notification Queue

### ISSUE THREAD

**Issue by yuchunc** [yuchunc/za_platform#12]
使用者右上角的小鈴鐺
收集對這個使用者重要的資訊

**Comment by yuchunc** [comment]
@irene84111 目前有哪些資訊對使用者重要到需要推給他們呢？

**Comment by yayinchang** [comment]
目前想到：
1. （已訂閱的）直播主開始直播
2. 有人傳訊息給你
3. （已訂閱的）直播主發了 News Feed （這個不一定需要啦 XD）

**Comment by yuchunc** [comment]
4. 有人Follow你了

**Comment by yuchunc** [comment]
我寫了一版 但是有不少問題
我想把這個放到後面重新寫一次

https://10consulting.com/2017/01/04/building-a-cqrs-web-application-in-elixir-using-phoenix/
https://github.com/commanded/eventstore
https://github.com/commanded/commanded
