### ISSUE TITLE
Copywriting: 關於 Zazaar

### ISSUE THREAD

**Issue by yayinchang** [yuchunc/za_platform#21]
- 成立動機
- 目標
- 特色 / 承諾 etc.

Ref: https://careers.shopee.tw/about/

**Comment by yuchunc** [comment]
雜雜（ZaZaar）取名於英文中東市集（BaZaar），為全球第一的即時直播購物平台。我們致力於為買賣雙方提供最佳的購物經驗，並用真人線上直播顛覆傳統的電商。
