### ISSUE TITLE
Copywriting: 服務條款

### ISSUE THREAD

**Issue by yayinchang** [yuchunc/za_platform#22]

**Comment by yuchunc** [comment]
本社群規範與用戶協議自 2018 年 09 月 01 日起生效。雜雜全體用戶與雜雜團隊需一同維護此社群，尊重雜雜上的每位用戶，並遵守以下規範：

雜雜貼文規範

請勿傳送謾罵留言、不雅文字、垃圾訊息、張貼不雅照片與影片，或任何您無權分享的照片與影片。
任何在雜雜張貼照片或影片的使用者皆可獲得分潤（視您的照片或影片受歡迎程度），但若您違反雜雜貼文規範，輕微者將被刪除該照片或影片，嚴重者將被刪除帳號。
雜雜直播規範

直播時禁止口出惡言、攻擊他人或自殘、猥褻裸露、吸毒或進行任何違法行為，亦不可使用危險道具（包含但不僅限於槍枝、刀具等）。
直播時需有主播出境互動，禁止長時間播放影片、電視電影、音樂或其他相冊錄像，或任何您無權分享的照片與影片。
任何在雜雜進行直播的使用者皆可賣東西，但若您違反雜雜直播規範，輕微者將被刪除該直播，嚴重者將被刪除帳號。
雜雜社群守則

因雜雜使用者年齡分佈廣泛，請用戶們發布適合各年齡層觀看的貼文（含照片、影片）與直播。
請用戶遵守法律，切勿在雜雜中提供性服務、買賣非法商品或藥物（即使該藥物在您的地區為合法藥物）。非法商品包含但不限於：盜版商品、槍枝、菸酒、保育類動物等。
請勿在雜雜中播放有版權的影片、音樂，或違法散佈不屬於您的影音內容。若您觸犯著作權法，須自行承擔後果，且雜雜官方將配合警方調查並提供相關資料。
重要提示：當您下載雜雜並註冊雜雜帳號，即代表您同意雜雜的使用條款、隱私權政策、社群規範與用戶協議。以上規範適用於所有雜雜用戶，如有發現違反規範之行為，嚴重者的帳號將永久停權。遭停權之帳號將無法復原。

雜雜官方有選擇用戶的權利，並保留所有規定的解釋權，雜雜亦有權於任何時間修改或變更本協議之內容。本協議如有任何重大變更或修正，將不另行通知。

**Comment by yuchunc** [comment]
先用這個好了
(從 17 那邊改的 😝
