### ISSUE TITLE
套件: Phoenix Inline SVG

### ISSUE THREAD

**Issue by yayinchang** [yuchunc/za_platform#32]
安裝套件 [Phoenix Inline SVG](https://hexdocs.pm/phoenix_inline_svg/readme.html)

將預設路徑改為 `assets/static/images`

**Comment by yuchunc** [comment]
這個 merge 回 master 了
設定上應該是沒問題 只是很奇怪 inline svg 沒有顯示人和圖片 @@

**Comment by yuchunc** [comment]
@irene84111 試試看 不行再跟我說
