### ISSUE TITLE
Sidebar 用 CSS 來 truncate？

### ISSUE THREAD

**Issue by yuchunc** [yuchunc/za_platform#35]
https://github.com/ZaZaar/ZaZaar/blob/v1/lib/zazaar_web/templates/layout/sidebar.html.eex#L18-L20

或許可以用 CSS-based 的 truncation??

https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

**Comment by yayinchang** [comment]
好唷，我前天才知道有這招 XDDD

**Comment by yuchunc** [comment]
再麻煩你了~~ < O >

**Comment by yayinchang** [comment]
Done
