### ISSUE TITLE
直播主需要有個地方輸入 FB 的 Streaming Key

### ISSUE THREAD

**Issue by yuchunc** [yuchunc/za_platform#49]

**Comment by yayinchang** [comment]
不太懂你的意思，可以說明這個功能的作用還有希望放的位置嗎？

**Comment by yuchunc** [comment]
要直播到 FB 之前 直播主需要輸入一個 streaming key，有了這個 key 雜雜才能幫他直播到臉書
有沒有簡單的流程可以讓使用者輸入這個 Key？

我目前想到最簡單的方式是：
- 點 `開始直播` 的時候會先跳出 modal 問使用者要不要直播到臉書
or
- 在直播頁有多一個地方讓使用者輸入
