### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by yuchunc** [yuchunc/za_platform#6]
This describe the state of somewhere after Alpha and inbetween Beta
# User Roles
All Roles can see streams
**General Viewer (No Account)** Prompted to get an account.
**Viewer (Base User)** Can buy from sellers.
**Free Tier Seller** No monthly fee, high transaction fee
**Paid Tier Seller** Monthly fee, low transaction fee.

## Viewer Features
- Can Follow Sellers
- Can buy from Sellers
- Can Interacts with Streamer
- ＊Can set interested Category
- Logs in with FB or username and password
- ＊Can rate Transaction

## Free Tier Streamer Features
- Can livestream
- ＊Can start item auction (chatbot or shopping cart)
- High per item transaction fee

## Pay Tier Streamer Features
- Everything Free Tier Streamer can do
- ＊Can notify followers on stream time
- ＊Schedule Next Stream
- ＊Analytical tool
- Lower per item transaction fee

# Pages
## Homepage
- People sees a stream right a way
- List suggested Streams
- List the Categories

## Stream Show page
- Sees the selected stream
- A pin message
- A comment box
- User can follow the Streamer

## Sign-in Page
- Login with Username Password
- Login with Facebook

## User Setting Page
- Sets basic information (name, birthday, contact information, avatar)
- notification settings

## Streaming Page
- Can start a stream here
- See the current Viewer count
- See the list of Viewers
- Comment box to interact with Viewers
- Possibilly an ongoing  bar chart of Viewer count

**Comment by ghost** [comment]
This describe the state of somewhere after Alpha and inbetween Beta
# User Roles
All Roles can see streams
**General Viewer (No Account)** Prompted to get an account.
**Viewer (Base User)** Can buy from sellers.
**Free Tier Seller** No monthly fee, high transaction fee, 
**Paid Tier Seller** Monthly fee, low transaction fee.
can you plz give more details about how 'high/low transaction fee' works?

## Viewer Features
- Can Follow Sellers
- Can buy from Sellers
- Can Interacts with Streamer
- Can set interested Category
- Logs in with FB or username and password
- Can rate Transaction
If the buyer can rate the seller, is that mean:
the seller can collect some kind of reward, what is the reward? or what is the rating system?

## Free Tier Streamer Features
- Can livestream
- Can start item auction (chatbot or shopping cart)
- High per item transaction fee
need a further information about shopping cart or chatbot

## Pay Tier Streamer Features
- Everything Free Tier Streamer can do
- Can notify followers on stream time
- Schedule Next Stream
- Analytical tool

like Google analyse? or what sort of analytical tool you are thinking?

# Pages
## Homepage
- People see a stream right away / whos stream are allowed on the first homepage?
- List suggested Streams
- List the Categories

## Stream Show page
- Sees the selected stream
- A pin message
- A comment box
- User can follow the Streamer

## Sign-in Page
- Login with Username Password
- Login with Facebook

## User Setting Page
- Sets basic information (name, birthday, contact information, avatar)
- notification settings

## Streaming Page
- Can start a stream here
- See the current Viewer count
- See the list of Viewers
- Comment box to interact with Viewers
- Possibilly an ongoing  bar chart of Viewer count

**Comment by yuchunc** [comment]
> can you plz give more details about how 'high/low transaction fee' works?

This is an example:
high transaction fee - 5 ~ 6%
low transaction fee - 2 ~ 3%
這部分還要精算過

> If the buyer can rate the seller, is that mean:
the seller can collect some kind of reward, what is the reward? or what is the rating system?

就像在ebay 或 pchome 上 可以看到賣家的評價

> need a further information about shopping cart or chatbot

這部分不會那麼快 alpha 版還是 focus 再讓 stream 順利

> like Google analyse? or what sort of analytical tool you are thinking?

大概這個概念 但是 Google Analytic 看的數字不太依樣，但是主要還是讓賣家可以知道比如：說他說什麼東西的時候大家反應好、星期幾的幾點賣得最好、觀看人的類別 等等的資料
