### ISSUE TITLE
Apply UIs Wireframe

### ISSUE THREAD

**Issue by yuchunc** [yuchunc/za_platform#9]
- [x] Default Layout
  - Navbar：Logo, Search Bar, Notification, Message, Log In, User Avatar
  - Side Bar：訂閱的直播主 (Live / Offline), Footer

- [x] Stream listing (Home)
  - 熱門直播列表
  - 正在直播：Guest ~ Random / Login ~ 依訂閱推播

- [x] Stream Viewing page
  - 直播視窗
  - 聊天室
  - 直播內容說明（By 直播主, Video Based）

- [x] Personal Page
  - 自我介紹 / 關於我
  - Streaming (if Live)
  -  影片存檔（關閉留言功能，僅供使用者參考用）

- [x] Log-in Modal
  - Facebook oAuth only

- [x] User Dashboard
  - 帳戶設定

**Comment by yuchunc** [comment]
@huaihuaiwu 再請給我估計時間囉~

**Comment by ghost** [comment]
所以template在哪？

**Comment by yuchunc** [comment]
那天就丟到 Line 上啦 @@

**Comment by yuchunc** [comment]
Irene [11:38 PM]

![default](https://user-images.githubusercontent.com/1594682/40907571-dc777cc6-6816-11e8-97bf-ac9d425d0590.jpg)

我花了點時間重新釐清目前第一版的架構，盡量以 MVP 的規模＋使用者希望有的最小功能來思考
這邊有幾點補充說明：
1. News Feed：可以的話還是希望有。最簡的版本即可：沒有留言，只有按讚。
2. DM 訊息：主要用來 Cover 購物車、金流的部分。讓買賣雙方私下聯絡處理得標後的後續流程。
3. 影片存檔：可以的話希望有。後來想想其實對陌生使用者來說，可以作為判斷的依據。在沒有開台的時間也可以了解該直播主的風格、頻率等等，進而決定要不要訂閱。也可以讓畫面不要那麼空啦 XD

Irene [11:43 PM]
另外，想問說使用者登入 / 註冊的部分，你想怎麼設計？（我沒碰過這方面的功能 QQ）
有提供 OAuth 嗎，有哪些資訊是使用者註冊需要的？名稱、信箱、電話 ...... ？
